### ISSUE TITLE
After fix for single coil setup, mower always turns right..

### ISSUE THREAD

**Issue by Ola-Palm** [sm6yvr/liam#16]
After the fix for making it possible to run the mower on a single coil setup, the mower always turns right.

Issue in Liam.ino 
For(number of sensors loop)
add new if(I==0)
turn right
else 
turn left.

**Comment by jonasnilton** [comment]
With fix 16 the mower miss the BWF signal and don't react. Kept latest BWF setting 86/5 as was working previously, but the mower escapes.

**Comment by Ola-Palm** [comment]
jonasnilton comment on this issue was not due to this fix.
