### ISSUE TITLE
Detect unreasonable behavour.

### ISSUE THREAD

**Issue by Datorsmurf** [sm6yvr/liam#36]
When Liam is caught up in a situation where he wheels are spinning without giving enough resistance for the wheel overload to trigger, this situation could be detected by using a timeout for how long time is reasonable to have between bumps or BWF-hits.

**Comment by thomasloven** [comment]
A simple fix, that can be improved greatly.

I like your idea on adjusting TURN_INTERVAL over time as the mower learns the area.
Leaving the issue open for now.
