### ISSUE TITLE
setup and debug mode removed in commit aec1e554b3cf7e08331786804690fabdd67f7d8c

### ISSUE THREAD

**Issue by poyaque-estamos** [sm6yvr/liam#40]
Can we have it back? The code is still there for it to be in definition.h again.

**Comment by thomasloven** [comment]
A new debug mode - which doesn't require recompiling - will be available in the 5.3-RC release, which will probably be about in a day or two.

If you're impatient, you could check out the `develop` branch, which already contains the new mode.

The debug mode is accessed by sending a `d` or `D` to the arduino via the serial console within five seconds of the mower starting.

**Comment by thomasloven** [comment]
5.3 rc1 has just been released, containing the debug mode.

https://github.com/sm6yvr/liam/tree/5.3-rc1

**Comment by poyaque-estamos** [comment]
Great! Thanks!
