### ISSUE TITLE
Compile error with 5.4.0

### ISSUE THREAD

**Issue by bphermansson** [sm6yvr/liam#46]
I can't compile the latest version:

'POSITIVE' was not declared in this scope

Where shall it be declared?

**Comment by thomasloven** [comment]
It's supposed to be declared by the `LiquidCrystal_I2C` library.
You can find the correct libraries here: https://github.com/sm6yvr/liam/releases/tag/5.3-rc1

**Comment by bphermansson** [comment]
Ok great! Seems to work with the latest version of the lib to, downloaded from https://bitbucket.org/fmalpartida/new-liquidcrystal/src/integration/.
